words = [
    "adr",
    "ansible",
    "arcticicestudio",
    "arn",
    "autonumber",
    "autopep",
    "awscli",
    "ble",
    "breakpoint",
    "ccls",
    "cdk",
    "charmbracelet",
    "clippy",
    "cmake",
    "coconutbattery",
    "colorcolumn",
    "colordiff",
    "completeopt",
    "ctags",
    "curdir",
    "debuginfo",
    "dyn",
    "ecosia",
    "emmylua",
    "envconfig",
    "eob",
    "expandtab",
    "facto",
    "fillchars",
    "fira",
    "foldclose",
    "foldcolumn",
    "foldenable",
    "foldexpr",
    "foldlevelstart",
    "foldmethod",
    "foldopen",
    "foldsep",
    "fwcd",
    "fzf",
    "ghostery",
    "gopls",
    "hammerspoon",
    "hbenl",
    "higroup",
    "hmac",
    "iam",
    "iterm",
    "jsonnet",
    "kpi",
    "kube",
    "lfs",
    "libgit",
    "liveshare",
    "luarocks",
    "mapleader",
    "menuone",
    "meslo",
    "mhutchie",
    "mockable",
    "mockall",
    "moia",
    "monitorcontrol",
    "mru",
    "neovim",
    "noinsert",
    "nop",
    "nord",
    "noremap",
    "noselect",
    "nvim",
    "openjdk",
    "pixelmator",
    "podman",
    "powerline",
    "protoc",
    "pyenv",
    "pylance",
    "recents",
    "reqwest",
    "ripgrep",
    "rustfmt",
    "rustls",
    "rustup",
    "scalameta",
    "scrolloff",
    "semconv",
    "serde",
    "sessionoptions",
    "shellcheck",
    "shfmt",
    "shiftwidth",
    "smoothscroll",
    "softtabstop",
    "splitbelow",
    "splitright",
    "sqs",
    "starship",
    "staticcheck",
    "steinke",
    "stylua",
    "swellaby",
    "tabpages",
    "tabstop",
    "termguicolors",
    "tilesize",
    "titlestring",
    "tokio",
    "traceparent",
    "uber",
    "undofile",
    "virtualenv",
    "vscode",
    "vscodevim",
    "webhooks",
    "webpki",
    "wget",
    "winpos",
    "winsize",
    "wipr",
    "withf",
    "xyz",
    "zoxide",
    "zplug",
]
