words = [
    "ansible",
    "arcticicestudio",
    "arn",
    "autopep",
    "awscli",
    "ccls",
    "cdk",
    "charmbracelet",
    "clippy",
    "cmake",
    "coconutbattery",
    "colordiff",
    "ctags",
    "ecosia",
    "emmylua",
    "fira",
    "fwcd",
    "fzf",
    "ghostery",
    "gopls",
    "hammerspoon",
    "hbenl",
    "iam",
    "iterm",
    "jsonnet",
    "kube",
    "lfs",
    "libgit",
    "liveshare",
    "luarocks",
    "meslo",
    "mhutchie",
    "moia",
    "monitorcontrol",
    "mru",
    "neovim",
    "nord",
    "openjdk",
    "pixelmator",
    "podman",
    "powerline",
    "pyenv",
    "pylance",
    "recents",
    "reqwest",
    "ripgrep",
    "rustfmt",
    "rustls",
    "rustup",
    "scalameta",
    "semconv",
    "serde",
    "shellcheck",
    "shfmt",
    "starship",
    "staticcheck",
    "stylua",
    "swellaby",
    "tilesize",
    "tokio",
    "traceparent",
    "virtualenv",
    "vscode",
    "vscodevim",
    "webhooks",
    "webpki",
    "wget",
    "wipr",
    "zoxide",
    "zplug",
]
